### ISSUE TITLE
-27V output from Twin Peaks?

### ISSUE THREAD

**Issue by jaschanarveson** [victorkashirin/CellaVCV#3]
I just hooked up Twin Peaks with a manual gate trigger and am getting a crazy -27V output.  

With no input to Twin Peaks it still outputs -27V.

Stepped output from Random like in the manual's example is still in the -27V range.

**Comment by victorkashirin** [comment]
@jaschanarveson Thank you for the report. Would you be able to share patch? I'm not able to reproduce this state.

**Comment by victorkashirin** [comment]
@jaschanarveson Thank you for the report.  Was able to reproduce with number of threads > 1, will debug.

**Comment by victorkashirin** [comment]
@jaschanarveson issue has been fixed, update will be in the library within a week.

**Comment by victorkashirin** [comment]
@jaschanarveson fixed version was release to the library

**Comment by jaschanarveson** [comment]
Wonderful - playing with it now.  It sounds great!

**Comment by Petervos2018** [comment]
EDIT : All is well now , after loading TP in a fresh VCV project, sorry for the fuzz....


Hi just installed 2.0.5 because I had the -12V problem, but it's not fixed for me  

Win 10 VCV Rack 2.6.0

![afbeelding](https://github.com/user-attachments/assets/534702a8-9f2f-48a6-935d-df9d508ae889)

![TP](https://github.com/user-attachments/assets/52ff4d09-7109-4298-909b-41b95a167065)


P.S If I remove TP and add a new one it (sometimes) outputs -12V straight away.
